export const MODEL_REGISTRY = [
  {
    id: 'all-MiniLM-L6-v2',
    name: 'MiniLM L6 v2',
    description: 'Small, fast model good for general-purpose semantic similarity. No input prefix required.',
    dimensions: 384,
    sizeBytes: 91000000,
    speed: 0.9,
    quality: 0.7,
    queryPrefix: null,
    documentPrefix: null,
    pooling: 'mean',
    normalize: true,
    huggingFaceId: 'Xenova/all-MiniLM-L6-v2',
  },
  {
    id: 'bge-small-en-v1.5',
    name: 'BGE Small English v1.5',
    description: 'Strong retrieval quality with compact size. Requires query/passage prefixes (handled automatically).',
    dimensions: 384,
    sizeBytes: 130000000,
    speed: 0.8,
    quality: 0.85,
    queryPrefix: 'query: ',
    documentPrefix: 'passage: ',
    pooling: 'cls',
    normalize: true,
    huggingFaceId: 'Xenova/bge-small-en-v1.5',
  },
  {
    id: 'gte-small',
    name: 'GTE Small',
    description: 'Compact general text embeddings model. No input prefix required.',
    dimensions: 384,
    sizeBytes: 120000000,
    speed: 0.8,
    quality: 0.85,
    queryPrefix: null,
    documentPrefix: null,
    pooling: 'mean',
    normalize: true,
    huggingFaceId: 'Xenova/gte-small',
  },
  {
    id: 'nomic-embed-text-v1.5',
    name: 'Nomic Embed Text v1.5',
    description: 'High-quality 768-dim embeddings. Larger but excellent retrieval accuracy. Requires search prefixes (handled automatically).',
    dimensions: 768,
    sizeBytes: 550000000,
    speed: 0.5,
    quality: 0.95,
    queryPrefix: 'search_query: ',
    documentPrefix: 'search_document: ',
    pooling: 'mean',
    normalize: true,
    huggingFaceId: 'nomic-ai/nomic-embed-text-v1.5',
  },
  {
    id: 'bge-base-en-v1.5',
    name: 'BGE Base English v1.5',
    description: 'High-quality 768-dim English embeddings with strong benchmark performance. Requires query/passage prefixes (handled automatically).',
    dimensions: 768,
    sizeBytes: 440000000,
    speed: 0.4,
    quality: 0.95,
    queryPrefix: 'query: ',
    documentPrefix: 'passage: ',
    pooling: 'cls',
    normalize: true,
    huggingFaceId: 'Xenova/bge-base-en-v1.5',
  },
];
